
# 1. Guix verilator package (need version 4.110)
# 2. Guix dtc package
# 3. ariane
# 4. libfesvr.a (get this from Guix spike package?)
# 5. cross-compile Guix pk package
# 6. cross-compile Guix hello package

# Setup a working directory

export TOP=$PWD/work
mkdir -p ${TOP}
cd ${TOP}

# guix install verilator 4.110

cat > verilator-4.110.scm \
<<'END'
(use-modules (gnu packages fpga)
             (guix packages)
             (guix git-download))

(package
  (inherit verilator)
  (version "4.110")
  (source (origin
            (inherit (package-source verilator))
            (uri (git-reference
                   (url "https://github.com/verilator/verilator")
                   (commit (string-append "v" version))))
            (sha256 (base32 "1lm2nyn7wzxj5y0ffwazhb4ygnmqf4d61sl937vmnmrpvdihsrrq")))))
END

guix package --install-from-file=verilator-4.110.scm

# guix install device tree compiler

guix install dtc

# guix install gcc toolchain, we need to do this explicitly because we
# need to use the same version of gcc that we used to compile verilator
# when we actually compile the C++ code generated by Verilator (i.e.,
# when we do `make verilate` below ... once we package Ariane we won't
# need to install gcc-toolchain?

guix install gcc-toolchain

# clone Ariane (from BRG copy)

#git clone --recursive https://github.com/openhwgroup/cva6.git
git clone --recursive git@github.com:cornell-brg/cva6.git

# Maybe we want a separate package to build the fesvr? This part should
# be pretty straight-forward? The fesvr is here:
#
#  https://github.com/riscv/riscv-isa-sim.git
#
# Actually ... we already do package this in the Guix spike package:
#
#  https://git.savannah.gnu.org/cgit/guix.git/tree/gnu/packages/virtualization.scm#n1011
#
# I think the diference is the spike package does not currently install
# libfesvr.a so maybe we just need to modify the spike package to do
# that?

#cd $TOP/cva6
#ci/make-tmp.sh
#ci/install-fesvr.sh

# Generate verilator binary ... this is the actual "building" part where
# we create teh simulator.

cd $TOP/cva6
make verilate -j64

# guix install riscv-pk

cd $TOP
TMPDIR=$(guix build --target=riscv64-linux-gnu riscv-pk)
ln -sf $TMPDIR/bin/pk

# guix install hello-static

cd $TOP
cat > hello-static.scm \
<<'END'
(use-modules (gnu packages base)
             (guix build-system gnu))

(define hello-static
 (static-package hello))

hello-static
END

TMPDIR=$(guix build --target=riscv64-linux-gnu -f hello-static.scm)
ln -sf $TMPDIR/bin/hello

# guix install smith-waterman

cd $TOP
TMPDIR=$(guix build --target=riscv64-linux-gnu smithwaterman-static)
ln -sf $TMPDIR/bin/smithwaterman

# Run cross-compiled hello

cd $TOP/cva6
work-ver/Variane_testharness +time_out=10000000 $TOP/pk $TOP/hello

# Run cross-compiled smith-waterman

cd $TOP/cva6
work-ver/Variane_testharness +max-cycles=100000000 +time_out=100000000 $TOP/pk $TOP/smithwaterman -p TGATTGTACCAAA TGATCATGTACCA
