#=========================================================================
# guix-ariane/build.sh
#=========================================================================
# These are the steps we came up with to build Ariane and run with all
# dependencies being satisfied through existing Guix packages:
#
#  0. Setup
#  1. install Guix verilator package (need version 4.110)
#  2. install Guix qemu, spike packages
#  3. install Guix gcc-toolchain package
#  4. build ariane from source (with a few small changes)
#  5. cross-compile Guix pk package
#  6. cross-compile Guix hello package and run on qemu, spike, Ariane
#  7. cross-compile Guix smithwaterman package and run on qemu, spike, Ariane

#-------------------------------------------------------------------------
# 0. Setup
#-------------------------------------------------------------------------
# We need the guix-bioinformatics channel to get access to the static
# hellow and smithwaterman packages.

 % cd $HOME/.config/guix
 % cat > channels.scm \
<<'END'
(use-modules (guix ci))

(list
  (channel
    (name   'gn-bioinformatics)
    (url    "https://git.genenetwork.org/guix-bioinformatics/guix-bioinformatics.git")
    (branch "master"))
  (channel-with-substitutes-available
    %default-guix-channel "https://ci.guix.gnu.org"))
END

# Setup a working directory

export TOP=$PWD/work
mkdir -p ${TOP}
cd ${TOP}

#-------------------------------------------------------------------------
# 1. install Guix verilator package (need version 4.110)
#-------------------------------------------------------------------------

cat > verilator-4.110.scm \
<<'END'
(use-modules (gnu packages fpga)
             (guix packages)
             (guix git-download))

(package
  (inherit verilator)
  (version "4.110")
  (source (origin
            (inherit (package-source verilator))
            (uri (git-reference
                   (url "https://github.com/verilator/verilator")
                   (commit (string-append "v" version))))
            (sha256 (base32 "1lm2nyn7wzxj5y0ffwazhb4ygnmqf4d61sl937vmnmrpvdihsrrq")))))
END

guix package --install-from-file=verilator-4.110.scm

#-------------------------------------------------------------------------
# 2. install Guix qemu, spike packages
#-------------------------------------------------------------------------

guix install qemu

# We thought we might need to install the dtc package from guix since the
# Ariane instructions mention device-tree-compiler, but it looks like
# this is only need to build spike/fesvr. Since we will install
# spike/fesvr via guix we don't need to install the dtc package.

# Ariane basically does the same thing as Spike, so when building Ariane,
# we need to link against libfesvr.a. This is the front-end server code
# that is used when running programs with the proxy kernel. We figured
# out that we can just install spike using Guix, and that will install
# libfesvr.a here:
#
#  $GUIX_PROFILE/lib/libfesvr.a
#
# Then the Ariane build system will find it there and link against it.

guix install spike

#-------------------------------------------------------------------------
# 3. install Guix gcc-toolchain package
#-------------------------------------------------------------------------
# We need explicitly install the gcc-toolchain because we need to use the
# same version of gcc that we used to compile verilator when we actually
# compile the C++ code generated by Verilator (i.e., when we do `make
# verilate` below ... once we package Ariane we won't need to install
# gcc-toolchain?

guix install gcc-toolchain
source "$GUIX_PROFILE/etc/profile"

#-------------------------------------------------------------------------
# 4. build ariane from source (with a few small changes)
#-------------------------------------------------------------------------
# Clone Ariane. We started by doing this:
#
# git clone --recursive https://github.com/openhwgroup/cva6.git
#
# But note below we are cloning from our BRG fork. We needed to make the
# following changes to get Ariane to compile:
#
#  https://github.com/cornell-brg/cva6/commit/5f802b0520d91ee4a8c988fd83c66b0b48e75447
#
# Basically we needed to: (1) modify the LDFLAGS since we can find
# libfesvr.a from the guix package and we don't really need the RISCV
# stuff? and (2) make sure the simulation doesn't stop too early so we
# can see the output from our program.
#
# I guess we will need to patch the upstream version of Ariane during the
# package build process to make this work?

git clone --recursive git@github.com:cornell-brg/cva6.git

# Generate verilator binary ... this is the actual "building" part where
# we create the simulator.

cd $TOP/cva6
make verilate -j64

#-------------------------------------------------------------------------
# 5. cross-compile Guix pk package
#-------------------------------------------------------------------------
# As mentioned above, Ariane uses the same approach as spike, so we need
# to cross-compile the proxy kernel. We can do this using Guix.

cd $TOP
TMPDIR=$(guix build --target=riscv64-linux-gnu riscv-pk)
ln -sf $TMPDIR/bin/pk

#-------------------------------------------------------------------------
# 6. cross-compile Guix hello package and run on qemu, spike, Ariane
#-------------------------------------------------------------------------

cd $TOP
TMPDIR=$(guix build --target=riscv64-linux-gnu hello-static)
ln -sf $TMPDIR/bin/hello

# Run cross-compiled hello on qemu, spike, and Ariane. Notice we need to
# use a longer time out because it takes a long time to run this program.
# Ariane is a very detailed RTL simulator. It can take 30min to run
# hello ... but it works!

cd $TOP
qemu-riscv64 ./hello
spike ./pk ./hello
cva6/work-ver/Variane_testharness +time_out=10000000 ./pk ./hello

#-------------------------------------------------------------------------
# 7. cross-compile Guix smithwaterman package and run on qemu, spike, Ariane
#-------------------------------------------------------------------------

cd $TOP
TMPDIR=$(guix build --target=riscv64-linux-gnu smithwaterman-static)
ln -sf $TMPDIR/bin/smithwaterman

# Run cross-compiled smithwaterman on qemu, spike, and Ariane. Notice we
# need to use a longer time out because it takes a long time to run this
# program. Ariane is a very detailed RTL simulator. It can take 60min to
# run smithwaterman ... but it works!

cd $TOP
qemu-riscv64 ./smithwaterman -p TGATTGTACCAAA TGATCATGTACCA
spike ./pk ./smithwaterman -p TGATTGTACCAAA TGATCATGTACCA
work-ver/Variane_testharness +max-cycles=100000000 +time_out=100000000 ./pk ./smithwaterman -p TGATTGTACCAAA TGATCATGTACCA

